apiVersion: v1
kind: Pod
metadata:
  name: {{ template "wireguard.fullname" . }}
  labels:
    app: {{ template "wireguard.fullname" . }}
{{ include "wireguard.labels.standard" . | indent 4 }}
spec:
  volumes:
    - name: wg-config
      persistentVolumeClaim:
        claimName: {{ template "wireguard.fullname" . }}
    - name: host-volumes
      hostPath:
        path: /lib/modules
        type: Directory
  containers:
    - name: {{ .Chart.Name }}
      image: {{ template "wireguard.image" . }}
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      envFrom:
        - configMapRef:
            name: {{ template "wireguard.fullname" . }}
      securityContext:
        capabilities:
          add:
          - NET_ADMIN
          - SYS_MODULE
        privileged: true
      volumeMounts:
        - name: wg-config
          mountPath: /config
        - name: host-volumes
          mountPath: /lib/modules
      ports:
        - containerPort: {{ .Values.port }}
          protocol: UDP
      resources:
{{ toYaml .Values.resources | indent 12 }}