apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ring-mqtt.name" . }}
  labels:
{{ include "ring-mqtt.labels.standard" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "ring-mqtt.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "ring-mqtt.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
      - name: config
        secret:
          secretName: {{ template "ring-mqtt.name" . }}
          items:
            - key: config.json
              path: config.json
      - name: {{ template "ring-mqtt.name" . }}
        persistentVolumeClaim:
          claimName: {{ template "ring-mqtt.name" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ template "ring-mqtt.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /data/config.json
              subPath: config.json
              name: config
            - mountPath: /data
              name: {{ template "ring-mqtt.name" . }}
          resources:
{{ toYaml .Values.resources | indent 12 }}