apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ring-mqtt.fullname" . }}
  labels:
{{ include "ring-mqtt.labels.standard" . | indent 4 }}
type: Opaque
data:
  config.json: |
    {{ .Values.configuration | toJson | b64enc }}