apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "docker-registry.fullname" . }}
  labels:
{{ include "docker-registry.labels.standard" . | indent 4 }}
type: Opaque
data:
  config.yaml: |
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
    http:
      addr: :5000
      headers:
        X-Content-Type-Options:
        - nosniff
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
    version: 0.1