{{- if .Values.secrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "docker-registry.fullname" . }}
  labels:
{{ include "docker-registry.labels.standard" . | indent 4 }}
type: Opaque
data: {}
{{- end -}}