apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "unifi-controller.name" . }}
  labels:
{{ include "unifi-controller.labels.standard" . | indent 4 }}
spec:
  commonName: {{ .Values.host }}
  secretName: {{ template "unifi-controller.name" . }}
  dnsNames:
    - {{ .Values.host }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer