apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ template "unifi-controller.name" . }}
  labels:
{{ include "unifi-controller.labels.standard" . | indent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.host }}`)
      kind: Rule
      services:
        - name: {{ template "unifi-controller.name" . }}
          kind: Service
          port: 8443
          passHostHeader: true
          scheme: https
          sticky:
            cookie:
              sameSite: none
          serversTransport: {{ template "unifi-controller.name" . }}
  tls:
    secretName: {{ template "unifi-controller.name" . }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: {{ template "unifi-controller.name" . }}-discovery
spec:
  entryPoints:
    - discovery
  routes:
    - services:
        - name: {{ template "unifi-controller.name" . }}-discovery
          port: 10001
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ template "unifi-controller.name" . }}-provisioning
spec:
  entryPoints:
    - provisioning
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ template "unifi-controller.name" . }}
          port: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ template "unifi-controller.name" . }}-speed-test
spec:
  entryPoints:
    - speed-test
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ template "unifi-controller.name" . }}-speed-test
          port: 6789
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: {{ template "unifi-controller.name" . }}-stun
spec:
  entryPoints:
    - stun
  routes:
    - services:
        - name: {{ template "unifi-controller.name" . }}-stun
          port: 3478
