{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "unifi-controller.fullname" . }}
  labels:
{{ include "unifi-controller.labels.standard" . | indent 4 }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "unifi-controller.name" $ }}
                port:
                  number: 8080
    {{- end }}
  tls:
    {{- range $host := .Values.ingress.hosts }}
    - secretName: {{ $host | include "unifi-controller.utils.tls" }}
      hosts:
        - {{ $host }}
    {{- end -}}
{{- end -}}
