{{- if .Values.secrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "unifi-controller.fullname" . }}
  labels:
{{ include "unifi-controller.labels.standard" . | indent 4 }}
type: Opaque
data: {}
{{- end -}}