apiVersion: v1
kind: Service
metadata:
  name: {{ template "unifi-controller.name" . }}
  labels:
{{ include "unifi-controller.labels.standard" . | indent 4 }}
spec:
  ports:
    - name: provisioning
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: ui
      port: 8443
      targetPort: 8443
      protocol: TCP
  selector:
    app: {{ template "unifi-controller.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "unifi-controller.name" . }}-discovery
  labels:
{{ include "unifi-controller.labels.standard" . | indent 4 }}
spec:
  ports:
    - port: 10001
      targetPort: 10001
      protocol: UDP
  selector:
    app: {{ template "unifi-controller.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "unifi-controller.name" . }}-speed-test
  labels:
{{ include "unifi-controller.labels.standard" . | indent 4 }}
spec:
  ports:
    - port: 6789
      targetPort: 6789
      protocol: TCP
  selector:
    app: {{ template "unifi-controller.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "unifi-controller.name" . }}-stun
  labels:
{{ include "unifi-controller.labels.standard" . | indent 4 }}
spec:
  ports:
    - port: 3478
      targetPort: 3478
      protocol: UDP
  selector:
    app: {{ template "unifi-controller.name" . }}
    release: {{ .Release.Name }}
