# Default values for docker-registry.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: ghcr.io/paynejacob/homelab-packages/docker-registry
  pullPolicy: Always

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 5000

persistence:
  enabled: true
  storageClassName: "ssd"
  accessMode: "ReadWriteMany"
  size: "50Gi"

ingress:
  enabled: false
  hosts:
  - docker-registry.localhost
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt

remoteURL: "https://registry-1.docker.io"

resources: {}

secrets: {}
