{{- if .Values.secrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "<CHARTNAME>.fullname" . }}
  labels:
{{ include "<CHARTNAME>.labels.standard" . | indent 4 }}
type: Opaque
data: {}
{{- end -}}