# Default values for wireguard-peer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: ghcr.io/paynejacob/homelab-packages/wireguard-peer
  pullPolicy: Always

resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "200m"

configSecret: "wg-config"
