apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mqtt.fullname" . }}
  labels:
{{ include "mqtt.labels.standard" . | indent 4 }}
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true
