apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mqtt.fullname" . }}
  labels:
{{ include "mqtt.labels.standard" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "mqtt.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "mqtt.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ template "mqtt.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 1883
              protocol: TCP
              name: mqtt
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 1883
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: 30
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 1883
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 1883
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /mosquitto/config/mosquitto.conf
              name: mosquitto-config
              subPath: mosquitto.conf
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - configMap:
            defaultMode: 420
            name: {{ template "mqtt.fullname" . }}
          name: mosquitto-config