apiVersion: v1
kind: Service
metadata:
  name: {{ template "mqtt.fullname" . }}
  labels:
{{ include "mqtt.labels.standard" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - targetPort: mqtt
      protocol: TCP
      name: mqtt
      port: 1883
  selector:
    app: {{ template "mqtt.name" . }}
    release: {{ .Release.Name }}
