# Default values for mqtt.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: ghcr.io/paynejacob/homelab-packages/mqtt
  pullPolicy: Always

ingress:
  enabled: false
  hosts:
  - mqtt.localhost
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt

resources: {}

secrets: {}
