# Default values for <CHARTNAME>.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: ghcr.io/paynejacob/homelab-packages/<CHARTNAME>
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 80

ingress:
  enabled: false
  hosts:
  - <CHARTNAME>.localhost
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m

resources: {}

secrets: {}
