apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "zigbee2mqtt.name" . }}
  labels:
{{ include "zigbee2mqtt.labels.standard" . | indent 4 }}
data:
  configuration.yaml: |
    log_output:
      - console

    mqtt:
      base_topic: zigbee2mqtt
      server: {{ .Values.mqtt_url }}

    serial:
      port: {{ .Values.device }}

    homeassistant: true