{{- if .Values.configuration.auth_enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "chartmuseum.fullname" . }}
  labels:
{{ include "chartmuseum.labels.standard" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  AUTH_USER: {{ randAlphaNum 12 | b64enc }}
  AUTH_PASSWORD: {{ randAlphaNum 12 | b64enc }}
{{- end -}}