apiVersion: v1
kind: Service
metadata:
  name: {{ template "chartmuseum.fullname" . }}
  labels:
{{ include "chartmuseum.labels.standard" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
  selector:
    app: {{ template "chartmuseum.name" . }}
    release: {{ .Release.Name }}
