# Default values for zigbee2mqtt.

image:
  repository: koenkk/zigbee2mqtt
  tag: 1.23.0
  pullPolicy: Always

mqtt_url: ""
device: /dev/ttyACM0
network_key: ""

resources: {}
nodeSelector: {}
tolerations: []

persistence:
  enabled: true
  storageClassName: ""
  accessMode: "ReadWriteMany"
  size: "10Mi"
