name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: bin/build
      - run: for chart in dist/*.tgz; do curl -s -u ${{ secrets.CHARTS_CREDENTIALS }} --data-binary @$chart https://charts.jacobapayne.com/api/charts; done
      - run: while read image; do docker push $image; done < dist/images.txt
